name: AWS Artifact Account Setup
## This workflow will setup and configure the "Artifact AWS Account". This acocunt
# holds all build artifacts for the application.

on:
  push:
    branches: [ "main" ]

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read

jobs:
  ConfigureMainAccount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      - uses: mikefarah/yq@v4.44.3
        with:
            cmd: yq -V



      - name: Read the account id of the Artifact account
        id: read_artifact_account_id
        run: |
          ARTIFACT_ACCOUNT_ID=$(yq eval '.aws_account_id' cd/artifact-account-config.yaml)
          # Set the value as an output
          echo "::set-output name=artifact_account_id::$ARTIFACT_ACCOUNT_ID"

      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.read_artifact_account_id.outputs.artifact_account_id }}:role/deploy
  
      - name: Configure Artifact Account
        env:
          GIT_REPOSITORY_NAME: ${{ github.repository }}
        run: |
          cf_template_file='./cd/cloudformation/artifact-account.yaml'
          stack_name='artifact-account-setup'
          ECR_REPOSITORY_NAME=$(echo "$GIT_REPOSITORY_NAME" | tr '[:upper:]' '[:lower:]')

          aws sts get-caller-identity
          
          aws cloudformation deploy \
            --template-file "$cf_template_file" \
            --parameter-overrides \
              RepoName="$ECR_REPOSITORY_NAME" \
            --stack-name "$stack_name"  \
            --no-fail-on-empty-changeset



